### ISSUE TITLE
RuntimeError: Failed to find the required information needed to start the game

### ISSUE THREAD

**Issue by jkace21** [Tom-the-Bomb/akinator.py#17]
Just imported the module and copied the test_sync.py code. Did not alter anything.

Traceback (most recent call last):
  File "e:\test.py", line 53, in <module>
    test()
  File "e:\test.py", line 17, in test
    first_question = aki.start_game()
                     ^^^^^^^^^^^^^^^^
RuntimeError: Failed to find the required information needed to start the game

**Comment by Tom-the-Bomb** [comment]
Hi,

I am able to reproduce the error, so it does seem like an internal issue I need to investigate. I am a bit busy recently but I'll take a look to try and figure something out but it might take a bit.

The error stems from the JSON missing a required field that was expected, not sure why, they could've changed something.

**Comment by infofbnr** [comment]
I'm still getting this problem.

**Comment by DanTVD** [comment]
> I'm still getting this problem.

same here
